# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # Allow coverage to drop by up to 5% before failing
        threshold: 5%
        # Target coverage (informational, doesn't fail)
        target: 80%
    patch:
      default:
        # New code should have at least 50% coverage
        target: 50%

# Ignore files that are hard to test (platform-specific branches)
ignore:
  - "tests/**/*"
  - "examples/**/*"
  - "external/**/*"
  - "libs/**/*"
  - "cmake/**/*"

# Comment settings for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
